export enum ERROR_MESSAGE {
  // Auth error messages
  SIGN_IN = 'SIGN_IN_ERROR',
  SIGN_UP = 'SIGN_UP_ERROR',
  LOG_OUT = 'LOG_OUT_ERROR',
  INVALID_TOKEN = 'INVALID_TOKEN_ERROR',

  // Transaction error messages
  TOTAL_AMOUNT = 'GET_TOTAL_AMOUNT_ERROR',
  EDIT_TRANSACTION = 'EDIT_TRANSACTION_ERROR',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION_ERROR',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION_ERROR',
  INVALID_TRANSACTION = 'INVALID_TRANSACTION_ERROR',

  // Default error messages
  UNKNOWN = 'UNKNOWN_ERROR',
}
